---

- name: install pkgs
  hosts: all
  become: yes
  become_user: root
  tasks:
  - import_role:
      name: testing
  - import_role:
      name: nekodeps
#  - import_role:
#      name: update_pkgs
#  - import_role:
#      name: base_pkgs
#   - import_role:
#       name: setup_zfs_store    
