---
#
# change new_user_account below to your own username!
#

- name: initial setup
  hosts: all
  become: yes
  become_user: root
  tasks:
  - import_role:
      name: networking
  - import_role:
      name: nekodeps
  - import_role:
      name: base_pkgs
  - import_role:
      name: setup_bash
  - import_role:
     name: openssh 
   - import_role:
      name: user_setup
  - import_role:
      name: base_x
   - import_role:
      name: remote_x11
  - import_role:
      name: ntp
  - import_role:
      name: findutils
  - import_role:
      name: security
  vars_files:
    - group_vars/default/vault.yml
    
  vars:
    ansible_become_pass:  '{{ su_password }}'
    new_user_account:       'dillera2'
    new_user_first_name:    'andy'
    new_user_last_name:     'diller'