---

- name: install pkgs
  hosts: all
  become: yes
  become_user: root
  tasks:
  - import_role:
      name: testing
  - import_role:
      name: nekodeps

  vars_files:
    - group_vars/default/vault.yml
    
  vars:
    ansible_become_pass: '{{ su_password }}'