- name: disable services
  shell: chkconfig {{ item }} off
  with_items:
    - webface_apache
    - webface
    - sgi_apache
    - numastatd
    - esp
    - lp
    - ipfilterd
    - sesdaemon
    - tfxd
    - snmpd
    - routed
    - route6d
    - sdpd
    - proclaim_server
    - ts
    - mkpd
    - visuallogin
    - autoconfig_ipaddress
  # failed_when: result.rc != 1
  # register: result
  ignore_errors: true
- name: stop services
  shell: /etc/init.d/{{ item }} stop
  with_items:
    - webface_apache
    - webface
    - sgi_apache
    - numastatd
    - esp
    - lp
    - ipfilterd
    - sesdaemon
    - tfxd
    - snmpd
    - routed
    - route6d
    - sdpd
    - proclaim_server
    - ts
    - mkpd
    - visuallogin
  ignore_errors: true
  tags: security


# stop bootp from going off via inetd
- name: Comment out bootp archive in /etc/inetd.conf
  replace:
    dest: /etc/inetd.conf
    regexp: '^bootp'
    replace: '#bootp'
  tags: security